url: "https://housegochimi.github.io"
baseurl: ""

# Site settings
title: 하우스 고치미
email: housegochimi@gmail.com
description: "집 고칠 일, 어디에 맡겨야 할지 막막할 때"

markdown: kramdown
sitemap: true

paginate: 12
paginate_path: "/repair/:num/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500

jekyll-archives:
  enabled:
    - tags
  layout: archive
  permalinks:
    tag: '/region=:name/'

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
